# -*- mode: ruby -*-
# vi: set ft=ruby :
BOX_NAME = "generic/ubuntu2204"
MEMORY = "4096"
CPUS = 1
VAGRANTFILE_API_VERSION = "2"

$install_docker_script = <<SCRIPT
echo "Installing dependencies ..."
sudo apt-get update
echo Installing Docker...
curl -sSL https://get.docker.com/ | sh
sudo usermod -aG docker vagrant
SCRIPT


Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    #Common setup
    config.vm.box = BOX_NAME
    config.vm.synced_folder ".", "/vagrant"
    config.vm.synced_folder "folderTmp", "/cache"
    config.vm.provision "shell",inline: $install_docker_script, privileged: true
    config.vm.boot_timeout = 800
    config.vm.provider "parallels" do |vb|
      vb.memory = MEMORY
      vb.cpus = CPUS
    end

    #Setup a set of nodes

    config.vm.define "node_1" do | node_1 |
        node_1.vm.network :private_network, ip: "192.168.56.10"
        node_1.vm.hostname = "node1"
      	node_1.vm.provision "shell", path: './setupsh/enableRemote.sh', privileged: true
        node_1.vm.provision "shell", path: './setupsh/enableRemoteTLS.sh', privileged: true
        #config.vm.synced_folder "./setupsh", "/app"
        #Only configure port to host for Manager01
        node_1.vm.network :forwarded_port, guest: 8080, host: 8088
        node_1.vm.network :forwarded_port, guest: 5000, host: 5050
        node_1.vm.network :forwarded_port, guest: 9000, host: 9090
        config.vm.provider :virtualbox do |vb|
          vb.customize ["modifyvm", :id, "--memory", MEMORY]
         # vb.customize ["modifyvm", :id, "--name", "node_1"]
          vb.customize ["modifyvm", :id, "--cpus", CPUS]
        end
    end

    config.vm.define "node_2" do | node_2 |
        node_2.vm.network :private_network, ip: "192.168.56.12"
        node_2.vm.hostname = "node2"
        node_2.vm.provision "shell", path: './setupsh/enableRemote.sh', privileged: true
        node_2.vm.provision "shell", path: './setupsh/enableRemoteTLS.sh', privileged: true
        #config.vm.synced_folder "./setupsh", "/app"
        #Only configure port to host for Manager01
          config.vm.provider :virtualbox do |vb|
          vb.customize ["modifyvm", :id, "--memory", MEMORY]
          vb.customize ["modifyvm", :id, "--cpus", CPUS]
        end
    end

    
end
