# -*- mode: ruby -*-
# vi: set ft=ruby :
BOX_NAME = "bento/ubuntu-22.04-arm64"
#config.vm.box = "generic/ubuntu2204"
#config.vm.box_version = "4.3.2"
MEMORY = "2048"
CPUS = 2
MANAGERS = 3
MANAGER_IP = "172.20.20.1"
WORKERS = 2
WORKER_IP = "172.20.20.10"
VAGRANTFILE_API_VERSION = "2"

$install_docker_script = <<SCRIPT
echo "Installing dependencies ..."
sudo apt-get update
echo Installing Docker...
curl -sSL https://get.docker.com/ | sh
sudo usermod -aG docker vagrant
SCRIPT

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  #Common setup
  config.vm.box = BOX_NAME
  config.vm.synced_folder ".", "/vagrant"
  config.vm.provision "shell",inline: $install_docker_script, privileged: true
  config.vm.boot_timeout = 800
  config.vm.synced_folder "folderTmp", "/cache"
  config.vm.provider "parallels" do |vb|
    vb.memory = MEMORY
    vb.cpus = CPUS
  end
  #Setup Manager Nodes
  (1..MANAGERS).each do |i|
      config.vm.define "manager0#{i}" do |manager|
        manager.vm.network :private_network, ip: "#{MANAGER_IP}#{i}"
        manager.vm.hostname = "manager0#{i}"
        if i == 1
          #Only configure port to host for Manager01
          manager.vm.network :forwarded_port, guest: 8080, host: 8088
          manager.vm.network :forwarded_port, guest: 5000, host: 5050
          manager.vm.network :forwarded_port, guest: 9000, host: 9090
        end
        config.vm.provision "shell", path: 'setup-cluster-swarm.sh', privileged: true
        config.vm.provision "shell", path: 'setupsh/enableRemoteTLS.sh', privileged: true
      end
  end

  #Setup Woker Nodes
  (1..WORKERS).each do |i|
      config.vm.define "worker0#{i}" do |worker|
          worker.vm.network :private_network, ip: "#{WORKER_IP}#{i}"
          worker.vm.hostname = "worker0#{i}"
          config.vm.provision "shell", path: 'setup-cluster-swarm.sh', privileged: true
      end
  end
end